### PR TITLE
Initial commit of submission publishing.

### PR DESCRIPTION
**Pull request by tokejepsen**
This PR extends the integration with an option to use Pyblish in the export dialog.

This allows developers to get all the exports the users want and validate and extract those. The user can now follow the normal workflow in NukeStudio of setting up presets to export, but still be publishing through Pyblish.

Unfortunately I wouldn't say the documentation for the exporting and submission is very extensive, but hopefully that'll change in the future.

### CODE REVIEW

**Comment by mkolar** [comment]
I've deployed pyblish-nukestudio last week, but didn't have enough time to properly test it, therefore at this point I can't really comment here much. We need to switch to pyblish full in nuke studio as well so I'll get to it fairly soon.

**Comment by tokejepsen** [comment]
Cool, look forward to your comments :)

For working with the submission publishing, you can get some inspiration from here; https://github.com/bumpybox/pyblish-bumpybox/tree/nukestudio_workflow/pyblish_bumpybox/plugins/nukestudio

**Comment by tokejepsen** [comment]
Hey @mkolar, did you have a chance to test this out?

It has been working here for a couple of weeks quite well.

**Comment by tokejepsen** [comment]
How do we feel about a merge for this?

**Comment by mkolar** [comment]
We still didn't deploy it, id it's working for you guys int he production I'd go ahead and merge.

**Comment by tokejepsen** [comment]
Got it in production here and been working nicely :)

@mottosso got any comments?

**Comment by mottosso** [comment]
Nope, I can't comment as I can't test nor use. Happy for you to run the show on this one.

**Comment by tokejepsen** [comment]
Thanks @mottosso.
Merging :)

**Pull request merged**
